---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - update
    - patch
    - delete
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - {{ template "falco-talon.name" . }}
  verbs:
    - use
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "falco-talon.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}