apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 5
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      serviceAccountName: {{.Values.name}}-sa
      securityContext:
        fsGroup: 65534 # to be able to read Kubernetes and AWS token files
      containers:
        - image: {{.Values.deployment.image}}:{{.Values.deployment.tag}}
          imagePullPolicy: Always
          name: {{.Values.name}}-container
          env:
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: endpoint
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: cluster_name
            - name: CW_POLLING
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: cw_polling
            - name: CW_FILTER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: cw_filter