apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Values.name }}-sa
    namespace: {{ .Release.Namespace }}
    annotations:
      eks.amazonaws.com/role-arn: "{{ .Values.serviceaccount.eks_role_arn }}"