customRules:
  custom-rules.yaml: |-
    - rule: Launch Sensitive Mount Container
      condition: >
        and not allow_container_images
      append: true
    
    - macro: allow_container_images
      condition: >
        container.image.repository in (allow_images)

    - list: allow_images
      items: [
        "quay.io/prometheus-operator/prometheus-operator", 
        "hashicorp/vault-k8s",
        "fluent/fluentd-kubernetes-daemonset",
        "prom/prometheus",
        "quay.io/kiali/kiali-operator", 
        "ibm_cloud_containers", 
        "public.ecr.aws/falcosecurity/falco",
        "kiwigrid/k8s-sidecar", 
        "sysdig/sysdig", 
        "falcosecurity/falco",
        "newrelic/infrastructure-k8s", 
        "quay.io/kiali/kiali", 
        "docker.io/falcosecurity/falco",
        "quay.io/prometheus/prometheus", 
        "quay.io/gravitational/teleport",
        "zooz/predator", 
        "docker.io/sysdig/sysdig", 
        "docker.elastic.co/beats/filebeat",
        "quay.io/prometheus/node-exporter", 
        "gcr.io/google_containers/hyperkube-amd64",
        "public.ecr.aws/aws-ec2/aws-node-termination-handler",
        "istio/pilot", 
        "gcr.io/google_containers/kube2sky",
        "gcr.io/kubecost1/kubecost-network-costs"
        ]

    - rule: Launch Privileged Container
      condition: >
        and not eks_container_img
      append: true

    - macro: eks_container_img
      condition: >
        container.image.repository in (eks_img_repository)

    - list: eks_img_repository
      items: [
        "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause",
        "k8s.gcr.io/provider-aws/aws-ebs-csi-driver",
        "gcr.io/kubecost1/kubecost-network-costs",
        "homolog-runner-deployment-8ksqc-22f7z"]

    - list: allowed_k8s_users_custom
      items: [
        "eks:certificate-controller", 
        "eks:k8s-metrics", 
        "github-actions", 
        "azure_ad_k8s_homolog", 
        "vsts-agent", "admin_sso", 
        "eks:pod-identity-mutating-webhook", 
        "admin_sso", "eks:support-engineer", 
        "eks:cluster-event-watcher", 
        "eks:nodewatcher", "eks:cluster-bootstrap",
        "eks:authenticator", "eks:pod-identity-mutating-webhook",
        "github-actions-application"
      ]

    - rule: Read secrets in /var/run/secrets
      desc: Detected reads in sensitive directory /var/run/secrets on administrative namespaces.
      condition: spawned_process and container.id != host and proc.cmdline contains /var/run/secrets/
      output: Possible extrafiltration ran inside a container (user=%user.name command=%proc.cmdline image=%container.image.repository)
      priority: WARNING
      tags: [k8s]
    
    - rule: Inbound SSH Connection
      desc: Detect Inbound SSH Connection
      condition: >
        ((evt.type in (accept,listen) and evt.dir=<) or
          (evt.type in (recvfrom,recvmsg))) and ssh_port
      output: >
        Inbound SSH connection (user=%user.name client_ip=%fd.cip client_port=%fd.cport server_ip=%fd.sip)
      priority: WARNING
      tags: [network]
      
    - rule: Outbound SSH Connection
      desc: Detect Outbound SSH Connection
      condition: >
        ((evt.type = connect and evt.dir=<) or
          (evt.type in (sendto,sendmsg))) and ssh_port
      output: >
        Outbound SSH connection (user=%user.name server_ip=%fd.sip server_port=%fd.sport client_ip=%fd.cip)
      priority: WARNING
      tags: [network]

    - rule: Detect su or sudo
      desc: detect sudo activities
      condition:
        spawned_process and proc.name in (sudo, su)
      output: >
        Detected sudo or su privilege escalation activity (user=%user.name command=%proc.cmdline)
      priority: WARNING
      tags: [process]

    - rule: Package Management Launched
      desc: detect package management launched
      condition: >
        spawned_process and user.name != "_apt" and package_mgmt_procs and not package_mgmt_ancestor_procs
      output: >
        Package management process launched in container (user=%user.name
        command=%proc.cmdline container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag)
      priority: ERROR
      tags: [process]

    - rule: Detect File Permission or Ownership Change
      desc: detect file permission/ownership change
      condition: >
        spawned_process and proc.name in (chmod, chown) and proc.args contains "/tmp/"
      output: >
        File below a known directory has permission or ownership change (user=%user.name
        command=%proc.cmdline file=%fd.name parent=%proc.pname pcmdline=%proc.pcmdline gparent=%proc.aname[2])
      priority: WARNING
      tags: [filesystem]
      
    - rule: Detect Directory Change
      desc: detect directories change
      condition: >
        spawned_process and proc.name in (mkdir, rmdir, mvdir, mv)
      output: >
        Directory Change in Filesystem (user=%user.name
        command=%proc.cmdline file=%fd.name parent=%proc.pname pcmdline=%proc.pcmdline gparent=%proc.aname[2])
      priority: WARNING
      tags: [filesystem]

    - macro: container_entrypoint
      condition: (not proc.pname exists or proc.pname in (runc:[0:PARENT], runc:[1:CHILD], runc, docker-runc, exe, docker-runc-cur))

    - macro: shell_procs
      condition: proc.name in (shell_binaries)

    - list: shell_binaries
      items: [ash, bash, csh, ksh, sh, tcsh, zsh, dash]

    - macro: user_expected_terminal_shell_in_container_conditions
      condition: (never_true)

    - rule: Suspicious Attempts to connect EC2 endpoint meta-data
      desc: Detect connections to/from a EC2 enndpoint meta-data with curl command. This indicates a possibility of sensitive data extrafiltration
      condition: (inbound_outbound) and proc.cmdline contains "curl -s 169.254.169.254/latest/"
      output: >
        Possibility of sensitive data extrafiltration. Detect connections to/from a EC2 enndpoint meta-data with curl command from container (command=%proc.cmdline connection=%fd.name user=%user.name container_id=%container.id %container.info image=%container.image.repository:%container.image.tag)
      priority: CRITICAL
      tags: [network]



      
      