name: Security Validation

on:
  push:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  security-fs:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-fs-scan.yml@main
    with:
      skipp_file: gitleaks-report.sarif
    secrets: inherit

  k8s-scan:
    needs: [security-fs]
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-k8s-scan.yml@main
    with:
      helmfile_dir: 'deploy/helmfile.yaml'
      env: 'labs'
    secrets: inherit

  #helm-validate:
    #needs: [security-fs, security-iac]
    #uses: igordevopslabs/custom-workflows-actions/.github/workflows/helmchart-test.yml@main
    #with:
      #application_name: falco-security
      #env: labs
      #helmfile_dir: deploy/helmfile.yaml
    #secrets: inherit