name: Security Validation

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

concurrency:
  group: security-checks-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scanning:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/gitleaks-scan.yml@main
    secrets: inherit

  security-fs:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-fs-scan.yml@main
    with:
      skipp_file: gitleaks-report.sarif
    secrets: inherit

  security-iac:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-iac-scan.yml@main
    with:
      env: labs
    secrets: inherit



